version: '3.1'

services:
  postgres:
    container_name: postgres_docker
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    expose:
      - "5433"
    ports:
      - "5433:5433"
    restart: always
    command: -p 5433

  pgadmin:
    container_name: pgadmin 
    image: dpage/pgadmin4
    restart: always 
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@root.com 
      - PGADMIN_DEFAULT_PASSWORD=root 
    ports:
      - "5050:80"
